### PR TITLE
Set contract properties to be optional

### PR DESCRIPTION
**Pull request by jnmt**
When registering contracts, contract properties should be optional. This patch fixes it.

### CODE REVIEW

**Comment by supl** [comment]
@jnmt 
It was a mistake. Thank you for fixing it.
Could you update the package version to `2.4.5`? (As it is a bugfix)
Thank you.

**Comment by jnmt** [comment]
@supl Thank you for reviewing. I updated the version to 2.4.5.

**Comment by supl** [comment]
> @supl Thank you for reviewing. I updated the version to 2.4.5.

@jnmt 
Thank you.
And I guess we also need to update `package-lock.json` file.
You can do that easily by the execute `npm install` command again,
then the package-lock.json file should be updated.

**Comment by supl** [comment]
> > @supl Thank you for reviewing. I updated the version to 2.4.5.
> 
> @jnmt
> Thank you.
> And I guess we also need to update `package-lock.json` file.
> You can do that easily by the execute `npm install` command again,
> then the package-lock.json file should be updated.

Ah, Sorry my bad.
I didn't notice you already did.
Github hides the diff of package-lock.json. Sorry!
LGTM.

**Comment by feeblefakie** [comment]
@jnmt @supl Thank you !
@supl Can you double check if there is any other similar issue ?

**Comment by scalarindetail** [comment]
> @jnmt @supl Thank you !
> @supl Can you double check if there is any other similar issue ?

No problem.
I will confirm the latest [doc](https://scalar-labs.github.io/scalardl/javadoc/client/)

**Comment by scalarindetail** [comment]
> @jnmt @supl Thank you !
> @supl Can you double check if there is any other similar issue ?

@feeblefakie 
I check the code and the document.
The only two optional arguments are
- functionArgument in executeContract
- properties in registerContract

It seems to me that the code for the validation after this PR is fine. 👍

**Comment by feeblefakie** [comment]
@supl Thanks !

**Pull request merged**
